Add metrics collection
avto-dev/app-metrics-laravel pull request #6
Opened 2019-09-25 08:37 UTC by tarampampam

| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes

## Description

## v1.1.0

### Added

- Interface `MetricsCollectionInterface`
- Formatters `JsonFormatter` and `PrometheusFormatter` now supports `MetricsCollectionInterface`

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I wrote unit tests for my code
- [x] I have made changes in [CHANGELOG.md](https://github.com/avto-dev/app-metrics-laravel/blob/master/CHANGELOG.md) file

2019-10-02 07:10 UTC, Reallife requested changes

2019-10-02 07:10 UTC, Reallife commented on src/Formatters/JsonFormatter.php
> +                        $result[$collection_item->name()] = (object) $this->metricToArray($collection_item);
Collisions if metrics in group have same names

2019-10-02 07:10 UTC, Reallife commented on src/Formatters/JsonFormatter.php
> +                        $result[$collection_item->name()] = (object) $this->metricToArray($collection_item);
fixed

2019-10-02 07:26 UTC, Reallife approved these changes

2019-10-02 07:28 UTC, merged

2019-10-08 18:03 UTC, tarampampam commented
@Reallife cbe36c72ce0916f403bff82f7c38a4db92012afc - wtf is this? I see backward incompatible changes and json formatter now returns array instead object with `property = metric name`. Collision can be only with invalid package configuration. Why you do this and publish release without my review?

2019-10-09 05:52 UTC, Reallife commented
@tarampampam Look, for example you have group of metrics:
```php
class SomeMetricGroup implements MetricsGroupInterface
{
    public function metrics(): iterable
    {
        foreach (['foo','bar'] as $label_value) {
            yield new SomeMetric($label_value);
        }
    }
}
```
and you have a metric:
```php
class SomeMetric implements MetricInterface, HasLabelsInterface
{
    protected $label_value;

    public function __construct(string $label_value)
    {
        $this->label_value    = $label_value;
    }

    public function labels(): array
    {
        return [
            'label_key' => $label_value,
        ];
    }
    
    public function name(): string
    {
        return 'some_metric';
    }

    public function value(): int
    {
        return 1;
    }
}
```
Metrics classes array in package config looks like (it's wrong config?):
```php
return [
    ...
    'metric_classes' => [
        App\Metrics\SomeMetricGroup::class,
    ],
   ... 
];
```

With old version of JsonFormatter you'll get something like that:
```json
{
  "some_metric": {
    "value": 1,
    "labels": {
      "label_key": "bar"
    }
  }
}
```

Metric with label's value `foo` was rewrited by metric with label's value `bar`.